### ISSUE TITLE
B2X300_PLA_PLA_v1.2.curaprofile causes bad prints

### ISSUE THREAD

**Issue by arqpedroloureiro** [beeverycreative/B2X300-resources#1]
The previous version of this profile was much better.
I tested the new one and the prints are terrible.
Not enough filament is coming out of the extruder and temperatures are low for the settings.
Gaps are created between the outlines and the inside fill.

If we use the old profile, everything is great.
b2x300 is a top printer, probably one of the best printers out there on this segment, 
Bee made a magnificent job with this great printer!
But people at bee must also be more carefull with cura profiles!

**Comment by tiagogala** [comment]
Hi @arqpedroloureiro!
I'm sorry to hear you're having issues printing on your B2X300. The printing profiles were thoroughly tested and we're having good results on our side, which is why I find your problems odd.

Can you confirm that you're using the printing profiles marked V1.2 (the latest to date) **and** you're using the Cura project also marked V1.2?

Also, are you using BEEVERYCREATIVE's filament? If so, which color and batch?

Thanks!

**Comment by ghost** [comment]
Hi @arqpedroloureiro and @tiagogala,

Altough I didn't use the previous printing profile versions I did found some changes in printing quality between the two extruders. Those might be due to the use of different colors. However, when I look in cura --> settings --> profile --> manage profile...  select B2X300_PLA_PLA_v1.2 I see under tab extruder e.g. 1 layer height 0.2 mm and extruder 2 layer height 0.3mm by default. There are other differences too. My assuption is that these Extruder 1/2 settings overwrite the global settings and which could explain the differences in print quality.

Hope that it helps...

**Comment by DomingosRodrigues** [comment]
Solved in commit 2f299cd76c647b51af205889737bad595d0f22b2
