### ISSUE TITLE
Error Slicing Using Ultimaker Cura 5.1.1

### ISSUE THREAD

**Issue by ManuelADSantos** [beeverycreative/B2X300-resources#4]
![Screenshot from 2022-10-27 11-33-38](https://user-images.githubusercontent.com/45367155/198262393-b8f3cf8f-c146-4ff3-af31-c69b8fea6066.png)

I cannot slice any piece

**Comment by DomingosRodrigues** [comment]
Hello Manuel, the profiles do not work on Cura 5.0 and 5.1 due to a bug inside Cura. 
I recommend using the officially supported version Cura 4.13.1 (available here https://github.com/Ultimaker/Cura/releases/tag/4.13.1 ) as that has been thoroughly tested and is working as intended for several objects. 
I have tested with good results, Cura version 5.2, it works if you delete the old profiles and re-import the cura profiles available on this github repository. The print quality appears to remain the same while cutting print times due to the new Arachne generator.

**Comment by DomingosRodrigues** [comment]
Closed
